from seating import build, reserve, toStr
import time

#This is an example using the provided initial setup
start = time.time()

seatMap = build(3, 11, ["R1C4","R1C6","R2C3","R2C7","R3C9","R3C10"])

seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 5)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 11)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 1)

print "\n"
print toStr(seatMap)

print("Time: %s secs" % (time.time() - start))

print "\n"
print "\n"
print "\n"

#Here is a larger version
start = time.time()

seatMap = build(25, 25, ["R1C4","R1C6","R2C3","R2C7","R3C9","R3C10"])

seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 13)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 5)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, -1)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 5)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 5)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 10)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 8)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 6)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 7)
seatMap = reserve(seatMap, 9)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 3)
seatMap = reserve(seatMap, 4)
seatMap = reserve(seatMap, 2)
seatMap = reserve(seatMap, 1)
seatMap = reserve(seatMap, 2)

print "\n"
print toStr(seatMap)

print("Time: %s secs" % (time.time() - start))
